# Catalog that supports Octybot
#WARNING: The name that your are going to asign, needs to be the same as the file that you want to call.
# The download file is in utils folder as download_models.sh and the ensure_model or validation is in utils.py

llm:
#Qwen Models
  - name: qwen2.5-3b-instruct-q4_k_m.gguf
    url: https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf?download=true

stt:
#Whisper models
  - name: base.pt
    url: "https://openaipublic.azureedge.net/main/whisper/models/ed3a0b6b1c0edf879ad9b11b1af5a0e6ab5db9205f891f668f8b0e6c6326e34e/base.pt"

  - name: small.pt
    url: "https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt"


tts:
#Piper Models
  - name: es_MX-claude-high.onnx
    url: https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/claude/high/es_MX-claude-high.onnx?download=true
    
  - name: es_MX-claude-high.onnx.json
    url: https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/claude/high/es_MX-claude-high.onnx.json?download=true
    
wake_word:
#Vosk Models
  - name: vosk-model-small-es-0.42
    url: https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip
